---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the kerberos packages 
  apt: name={{ item }} state=present update_cache=yes
  register: install
  with_items: kerberos_server_ubuntu_pkg

- name: Copy the kdc configuration file 
  template: src=kdc.conf.j2 dest=/etc/krb5kdc/kdc.conf
  notify: restart kerberos 

- name: Link /dev/random to /dev/urandom
  file: path=/dev/random src=/dev/urandom state=link force=yes

- name: Copy the kdc acl configuration file 
  template: src=kadm5.acl.j2 dest=/etc/krb5kdc/kadm5.acl
  notify: restart kerberos 

- name: Copy the client configuration file 
  template: src=krb5.conf.j2 dest=/etc/krb5.conf

- name: Create the initial kerberos database
  script: create_db.sh {{ kerberos_server_master_db_pass }} 
  when: install.changed

- name: Make sure we have the entry for hostname in /etc/hosts  
  host: ip={{ ansible_default_ipv4.address }} hostname={{ ansible_hostname }} aliases="{{ ansible_hostname + '.' + kerberos_server_realm_name|lower() }}"

- name: Start the kerberos services 
  service: name={{ item }} state=started enabled=yes
  with_items: kerberos_service

- name: Create an admin for the administering the kerberos database
  script: create_admin.sh  {{ kerberos_server_kadmin_pass }} {{ kerberos_server_kadmin_user }} 
  when: install.changed


